### ISSUE TITLE
Settings prefix inconsistency

### ISSUE THREAD

**Issue by kaedroho** [jacobtoppm/wagtail-image-import#17]
``WAGTAIL_IMAGE_IMPORT_GOOGLE_PICKER_API_KEY``
``WAGTAILIMAGEIMPORT_GOOGLE_OAUTH_CLIENT_SECRET``

**Comment by jacobtoppm** [comment]
Aha, thanks! Looks like that's just a typo on my part, the setting used is actually `WAGTAILIMAGEIMPORT_GOOGLE_PICKER_API_KEY`
